### ISSUE TITLE
[Feature Request] Have Meta + Numbers be able to launch/open windows on the dock

### ISSUE THREAD

**Issue by waw6** [pop-os/cosmic-dock#178] opened 2022-12-11 23:26 UTC
This is a thing on Dash to Dock, KDE, and Windows. It would be greatly appreciated if this feature was included.

**Comment by leviport** [comment] 2022-12-12 15:50
Duplicate of https://github.com/pop-os/cosmic-dock/issues/11

**Closed as completed by leviport** 2022-12-12 15:50 UTC
