### ISSUE TITLE
Settings fails to open due to `dock-alignment` key missing

### ISSUE THREAD

**Issue by bsdtux** [pop-os/cosmic-dock#172] opened 2022-10-05 03:16 UTC
received a brand new hp dev one laptop today and did an update on the laptop. Shortly after reboot I could no longer open up gnome-control-center. The error that I am getting is as follows

```shell
(gnome-control-center:9374): GLib-GIO-ERROR **: 22:10:21.587: Settings schema 'org.gnome.shell.extensions.dash-to-dock' does not contain a key named 'dock-alignment'
[1]    9374 trace trap (core dumped)  gnome-control-center

```

I have tried recreating the schema, copying the latest one, but nothing seems to help. Looking for any advice to get this working again

**Comment by bsdtux** [comment] 2022-10-05 03:57
Was able to fix it without really fixing it. I deleted my .config and .local directories and then logged out and back in and suddenly it seems like it was fixed

**Comment by coreyperkins** [comment] 2022-10-06 00:13
I am also seeing this, brand new machine (HPDEVONE). Opened, updated, then this in journalctl:

`░░ The job identifier is 374 and the job result is failed.
Oct 05 16:34:00 pop-os gnome-session-binary[1395]: GLib-CRITICAL: g_hash_table_foreach_remove_or_steal: assertion 'version == hash_table->version' failed
Oct 05 16:34:00 pop-os gdm-launch-environment][1194]: GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Oct 05 16:34:10 pop-os gnome-control-c[3515]: Settings schema 'org.gnome.shell.extensions.dash-to-dock' does not contain a key named 'dock-alignment'
Oct 05 16:35:21 pop-os gnome-control-c[4305]: Settings schema 'org.gnome.shell.extensions.dash-to-dock' does not contain a key named 'dock-alignment'
Oct 05 16:35:30 pop-os gnome-control-c[4354]: Settings schema 'org.gnome.shell.extensions.dash-to-dock' does not contain a key named 'dock-alignment'
Oct 05 18:37:01 pop-os gnome-control-c[6004]: Settings schema 'org.gnome.shell.extensions.dash-to-dock' does not contain a key named 'dock-alignment'
Oct 05 18:37:43 pop-os systemd[2680]: Failed to start Application launched by gnome-shell.
`

**Comment by jacobgkau** [comment] 2022-10-06 00:23
Interesting that they're both Dev Ones. I wonder if it's something to do with the image or imaging process being used for those. If anyone else sees this (especially on a computer other than the Dev One), please leave a comment.

The `dock-alignment` option was added way back in May: https://github.com/pop-os/cosmic-dock/pull/150 The key does exist on a fully-updated Pop!_OS system, so I'm not sure why it wouldn't be found.

I'll re-open this for a bit to help with triage.

**Comment by bsdtux** [comment] 2022-10-06 04:54
Let me know how I can help. I have tried a few things but none have resulted in a success. here is a list of things that I have tried

- strace -e trace=file gnome-control-center
- strace -e open gnome-control-center
- dconf write /org/gnome/shell/extensions/dash-to-dock/dock-alignment center (But I get the error below)

```shell
  ~ ❯ dconf write /org/gnome/shell/extensions/dash-to-dock/dock-alignment center
error: 0-6:unknown keyword

Usage:
  dconf write KEY VALUE 

Write a new value to a key

Arguments:
  KEY         A key path (starting, but not ending with '/')
  VALUE       The value to write (in GVariant format)

  ~ ❯ 

```

- I have also tried pulling down the latest zip from here and placing the schema xml in both locations `/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas` and `/usr/share/gnome-shell/extensions/cosmic-dock@system76.com/schemas/` and `~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/schemas` but those didn't help either. I even tried pulling down this repo and run make install hoping that would fix it. 


At this point I am pretty tapped out on what else I know how to do.

**Comment by coreyperkins** [comment] 2022-10-06 13:11
@jacobgkau I pulled down the latest pop put it on a bootable USB and did a full reinstall. The issues have not came back yet but if it does I'll update. In hindsight I wish I would have stuck with what I had to help debug but I was antsy to get the new rig how I wanted it.

**Comment by jacobgkau** [comment] 2022-10-06 15:16
@bsdtux Are you saying the issue is still occurring for you? I thought the issue stopped after you removed your `.config` and `.local` directories and re-logged.

This command `dconf write /org/gnome/shell/extensions/dash-to-dock/dock-alignment center` produces an error even on a system with no issues, FYI. Does `gsettings set org.gnome.shell.extensions.dash-to-dock dock-alignment CENTER` give you an error message? (For one thing, dconf only seems to have about a dozen keys available, while gsettings shows over a hundred; and for another thing, it seems that `CENTER` needs to be capitalized.)

The directory `/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/` should not exist at all on a default system. Have you tried to install the vanilla/upstream Dash to Dock somehow? (I can't replicate the issue just installing upstream Dash to Dock locally, but it goes into `.local/share` for me when I do that. I'm not sure that should matter, but trying to figure out what else might have been done on your system/image.)

**Comment by bsdtux** [comment] 2022-10-06 16:19
@jacobgkau I manually created the director `dash-to-dock@micxgx.gmail.com/` in hopes of solving it. As for deleting those directories I thought it solved it but if I click on gnome-control-center and then try and click on dock it crashes and starts throwing that error again. So I was a little premature in saying it was solved

When trying to run gsettings I get the following

```shell
  ~ ❯ gsettings set org.gnome.shell.extensions.dash-to-dock dock-alignment CENTER
No such key “dock-alignment”
  ~ ❯ 
```

**Comment by jacobgkau** [comment] 2022-10-06 16:31
How about `apt policy gnome-shell-extension-cosmic-dock` to confirm what version of it's installed? (Perhaps Settings should avoid crashing in cases like this, too, but that key really should be available.)

Someone is looking into the Dev One image as well, by the way, although I'm not sure how long that will take or if they'll be able to replicate.

**Comment by jacobgkau** [comment] 2022-10-06 16:32
Wait, it looks like that package may not be published right now, I only have it available from a staging repo:

```
system76@pop-os:~$ apt policy gnome-shell-extension-cosmic-dock
gnome-shell-extension-cosmic-dock:
  Installed: 72~ubuntu2pop0~1664903880~22.04~6700449
  Candidate: 72~ubuntu2pop0~1664903880~22.04~6700449
  Version table:
 *** 72~ubuntu2pop0~1664903880~22.04~6700449 500
        500 http://apt.pop-os.org/staging/master jammy/main amd64 Packages
        500 http://apt.pop-os.org/staging/master jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

Looking into this more (this would not be specific to the Dev One at all.)

**Comment by bsdtux** [comment] 2022-10-06 16:34
@jacobgkau ran the above just to see what I get and it looks like I get an older package compared to what you have.

```shell
  ~ ❯ apt policy gnome-shell-extension-cosmic-dock
gnome-shell-extension-cosmic-dock:
  Installed: 72~ubuntu2pop0~1650928261~22.04~8f33b3b
  Candidate: 72~ubuntu2pop0~1650928261~22.04~8f33b3b
  Version table:
 *** 72~ubuntu2pop0~1650928261~22.04~8f33b3b 100
        100 /var/lib/dpkg/status
  ~ ❯ 
```

**Comment by jacobgkau** [comment] 2022-10-06 16:34
I see what's going on. https://github.com/pop-os/repo-release/pull/178 released version https://github.com/pop-os/cosmic-dock/commit/40719914d6e39c11de1db56d6670dbe7d3f8aa42 of cosmic-dock, but CI for that version failed to build, so the package was un-published. (On your system, that means you kept an older version of cosmic-dock from before this key was added, while upgrading desktop-widget to a version that expects the key.) We have a more recent commit that has built, I'm working on getting that released now.

**Comment by jacobgkau** [comment] 2022-10-06 16:51
It looks like the current Dev One image was generated on May 4th, which explains why Dev Ones were particularly affected by this. (System76 images and the downloadable iso would have all been updated since the key was added to cosmic-dock in late May/early June.)

**Comment by bsdtux** [comment] 2022-10-06 16:54
@jacobgkau Should I sit tight until this becomes available for me to update in pop-os? As of now I am able to work around this for the most part so it isn't 100% blocker for me. More of a nice to have

**Comment by jacobgkau** [comment] 2022-10-06 16:56
Yes, https://github.com/pop-os/repo-release/pull/179 has been merged and CI is running now; after it's done in a few minutes, you'll just need to install updates again. I'll close this issue once CI has finished running and I'm able to confirm the release.

We're tracking the issue that allowed this to happen at https://github.com/pop-os/repo-release/issues/155. Apologies that this slipped by.

**Comment by bsdtux** [comment] 2022-10-06 16:59
@jacobgkau no worries. Thanks for helping me out. One day I hope to be more helpful in troubleshooting Pop OS and Linux issues and actually being able to contribute. For now I will take this as a small win / first step forward. :smile:

**Comment by jacobgkau** [comment] 2022-10-06 17:01
The current version of the package has been released again:

![image](https://user-images.githubusercontent.com/7199422/194374476-f8ca1993-f495-4d4a-a6c6-fc53ea5ddb21.png)

Any affected users can check for and install updates (using the Pop!_Shop or `sudo apt update`/`sudo apt full-upgrade`), which should resolve the issue.

**Closed as completed by jacobgkau** 2022-10-06 17:01 UTC

**Comment by bsdtux** [comment] 2022-10-06 17:07
@jacobgkau I can confirm that fixed it. I am now able to select the dock from gnome-control-center and adjust settings without it crashing anymore. Much appreciated for this

**Comment by aartyn4800git** [comment] 2022-10-06 17:18
Thanks, fixed for me now as well

**Comment by coreyperkins** [comment] 2022-10-06 22:08
You guys rock you were all over that!!
