### ISSUE TITLE
Disproportionate Dock in HD Resolution

### ISSUE THREAD

**Issue by rckmachado** [pop-os/cosmic-dock#99] opened 2021-12-17 13:34 UTC
The dock is totally out of proportion in HD resolution.

[Print](https://www.notion.so/rickmachado/Dock-Pop-_OS-21-10-2788335f2b4543f28520e7c0662130f5)

**Comment by leviport** [comment] 2021-12-17 17:43
Thanks for the report! I believe the issue is the applications library not scaling elegantly to smaller resolutions, not that the dock is sized incorrectly. Closing as a duplicate of https://github.com/pop-os/cosmic/issues/264

**Closed as completed by leviport** 2021-12-17 17:43 UTC
